name: unsareport-auth-dev

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '45000:5432'
    environment:
      POSTGRES_USER: idp
      POSTGRES_PASSWORD: idppassword
      POSTGRES_DB: idp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U idp -d idp_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
